export const REFERENCE_STOCK_CREATED_AT = "2026-05-29T00:00:00.000Z";

export const DEFAULT_REFERENCE_STOCK = [
  { id: "reference-cartucho-rl-uso-medio", categoria: "Agulhas e Cartuchos", nome: "Cartucho RL (Traço)", marca: "", linhaTipo: "Cartucho RL (Traço)", numeracao: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 15, quantidadeAtual: 20, quantidadeMinima: 2, unidadeMedida: "un" },
  { id: "reference-cartucho-rm-mg-uso-medio", categoria: "Agulhas e Cartuchos", nome: "Cartucho RM/MG (Pintura/Sombra)", marca: "", linhaTipo: "Cartucho RM/MG (Pintura/Sombra)", numeracao: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 15, quantidadeAtual: 20, quantidadeMinima: 2, unidadeMedida: "un" },
  { id: "reference-agulha-tradicional-haste", categoria: "Agulhas e Cartuchos", nome: "Agulha Tradicional Haste", marca: "", linhaTipo: "Agulha Tradicional Haste", numeracao: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 3, quantidadeAtual: 50, quantidadeMinima: 5, unidadeMedida: "un" },
  { id: "reference-aston-premium-rl-caixa", categoria: "Agulhas e Cartuchos", nome: "Aston Premium Cartucho RL 1007RL", marca: "Aston Premium", linhaTipo: "Cartucho RL", numeracao: "1007RL", formatoCompra: "box", quantidadeEmbalagem: 20, precoEmbalagem: 122, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-radiant-mr-caixa", categoria: "Agulhas e Cartuchos", nome: "Radiant Cartucho Magnum Round MR", marca: "Radiant", linhaTipo: "Cartucho Magnum Round", numeracao: "MR 0.30", formatoCompra: "box", quantidadeEmbalagem: 20, precoEmbalagem: 150, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-kwadron-rl-caixa", categoria: "Agulhas e Cartuchos", nome: "Kwadron Cartucho RL", marca: "Kwadron", linhaTipo: "Cartucho RL", numeracao: "Traço", formatoCompra: "box", quantidadeEmbalagem: 20, precoEmbalagem: 200, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-tinta-preta-linha", categoria: "Tintas", nome: "Tinta Preta Linha (Black Lining)", marca: "Dynamic Color Co", cor: "Preto Linha", quantidadeEmbalagem: 240, precoEmbalagem: 419.9, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "ml" },
  { id: "reference-tinta-preta-preenchimento", categoria: "Tintas", nome: "Tinta Preta Preenchimento", marca: "The Ink", cor: "Maximum's Black", quantidadeEmbalagem: 260, precoEmbalagem: 235, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "ml" },
  { id: "reference-tinta-colorida", categoria: "Tintas", nome: "Tinta Colorida", marca: "Electric Ink", cor: "Cores variadas", quantidadeEmbalagem: 30, precoEmbalagem: 78, quantidadeAtual: 4, quantidadeMinima: 1, unidadeMedida: "ml" },
  { id: "reference-electric-raven-black-30ml", categoria: "Tintas", nome: "Tinta Raven Black 30ml", marca: "Electric Ink", cor: "Raven Black", quantidadeEmbalagem: 30, precoEmbalagem: 85, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "ml" },
  { id: "reference-iron-works-colorida-30ml", categoria: "Tintas", nome: "Tinta Colorida 30ml", marca: "Iron Works", cor: "Cores variadas", quantidadeEmbalagem: 30, precoEmbalagem: 93.5, quantidadeAtual: 3, quantidadeMinima: 1, unidadeMedida: "ml" },
  { id: "reference-par-luvas-nitrilicas", categoria: "Biossegurança e Descartáveis", nome: "Par de Luvas Nitrílicas", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 2.5, quantidadeAtual: 50, quantidadeMinima: 10, unidadeMedida: "un" },
  { id: "reference-mascara-descartavel", categoria: "Biossegurança e Descartáveis", nome: "Máscara Descartável", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 1, quantidadeAtual: 50, quantidadeMinima: 10, unidadeMedida: "un" },
  { id: "reference-protetor-maca-lencol", categoria: "Biossegurança e Descartáveis", nome: "Protetor de Maca (Lençol)", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 3.5, quantidadeAtual: 20, quantidadeMinima: 5, unidadeMedida: "un" },
  { id: "reference-plastico-filme-uso", categoria: "Biossegurança e Descartáveis", nome: "Plástico Filme (Uso na maca/bancada)", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 2, quantidadeAtual: 30, quantidadeMinima: 5, unidadeMedida: "un" },
  { id: "reference-batoques-pmg", categoria: "Biossegurança e Descartáveis", nome: "Batoques P/M/G", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 0.5, quantidadeAtual: 100, quantidadeMinima: 20, unidadeMedida: "un" },
  { id: "reference-luvas-nitrilicas-caixa", categoria: "Biossegurança e Descartáveis", nome: "Par de Luvas Nitrílicas Caixa 100", marca: "Descarpack", formatoCompra: "box", quantidadeEmbalagem: 50, precoEmbalagem: 39.45, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-mascaras-caixa-50", categoria: "Biossegurança e Descartáveis", nome: "Máscara Tripla TNT Caixa 50", marca: "Descarpack", formatoCompra: "box", quantidadeEmbalagem: 50, precoEmbalagem: 14.19, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-batoque-jordan-100", categoria: "Biossegurança e Descartáveis", nome: "Batoque Solto P 100 unidades", marca: "Jordan Tattoo Supply", formatoCompra: "box", quantidadeEmbalagem: 100, precoEmbalagem: 7, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-papel-toalha-uso-medio", categoria: "Limpeza e Finalização", nome: "Papel Toalha (Uso médio)", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 3, quantidadeAtual: 30, quantidadeMinima: 5, unidadeMedida: "un" },
  { id: "reference-vaselina-manteiga-porcao", categoria: "Limpeza e Finalização", nome: "Vaselina / Manteiga Deslizante", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 3, quantidadeAtual: 30, quantidadeMinima: 5, unidadeMedida: "un" },
  { id: "reference-papel-hectografico-folha", categoria: "Limpeza e Finalização", nome: "Papel Hectográfico (Transfer)", marca: "", formatoCompra: "single", quantidadeEmbalagem: 1, precoEmbalagem: 3.5, quantidadeAtual: 20, quantidadeMinima: 5, unidadeMedida: "un" },
  { id: "reference-papel-hectografico-u20-20", categoria: "Limpeza e Finalização", nome: "Papel Hectográfico Roxo U20", marca: "U20", formatoCompra: "box", quantidadeEmbalagem: 20, precoEmbalagem: 25.99, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-papel-toalha-elite-1000", categoria: "Limpeza e Finalização", nome: "Papel Toalha Interfolha 1000 folhas", marca: "Elite", formatoCompra: "box", quantidadeEmbalagem: 1000, precoEmbalagem: 24.9, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "un" },
  { id: "reference-vaselina-hornet-500g", categoria: "Pastosos", nome: "Vaselina Hornet White Premium 500g", marca: "Hornet", quantidadeEmbalagem: 500, precoEmbalagem: 65, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "g" },
  { id: "reference-manteiga-reilly-500g", categoria: "Pastosos", nome: "Manteiga Blend Especial Reilly 500g", marca: "Reilly Tattoo", quantidadeEmbalagem: 500, precoEmbalagem: 89, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "g" },
  { id: "reference-plastico-filme-pvc-300m", categoria: "Materiais de Extensão", nome: "Plástico Filme PVC 28cm x 300m", marca: "Tecfilm", quantidadeEmbalagem: 300, precoEmbalagem: 30.51, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "m" },
  { id: "reference-tropicalderm-filme-5m", categoria: "Materiais de Extensão", nome: "Filme Protetor Para Tatuagem 10cm x 5m", marca: "TropicalDerm", quantidadeEmbalagem: 5, precoEmbalagem: 130, quantidadeAtual: 1, quantidadeMinima: 1, unidadeMedida: "m" }
];

export function clonarEstoqueReferencia() {
  return DEFAULT_REFERENCE_STOCK.map((item) => ({ ...item, criadoEm: REFERENCE_STOCK_CREATED_AT, atualizadoEm: REFERENCE_STOCK_CREATED_AT }));
}
